CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(256) UNIQUE NOT NULL,
    name VARCHAR(256)
    );

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) UNIQUE NOT NULL
    );

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    annotation VARCHAR(256) NOT NULL,
    description VARCHAR(256) NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    location_id BIGINT REFERENCES locations(id)ON DELETE CASCADE,
    initiator_id BIGINT REFERENCES users(id)ON DELETE CASCADE,
    event_date timestamp WITHOUT TIME ZONE,
    created_on timestamp WITHOUT TIME ZONE,
    published_on timestamp WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    paid BOOLEAN,
    participant_limit INTEGER,
    state VARCHAR(256),
    confirmed_requests BIGINT,
    views BIGINT
    );

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    pinned BOOLEAN
    );

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id)ON DELETE CASCADE,
    requester_id BIGINT REFERENCES users(id)ON DELETE CASCADE,
    state VARCHAR(256),
    created timestamp WITHOUT TIME ZONE
    );

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT REFERENCES compilations(id)ON DELETE CASCADE,
    event_id BIGINT REFERENCES events(id)ON DELETE CASCADE,
    PRIMARY KEY (compilation_id,event_id)
    );